format = """
[](#88C0D0)\
[ Tamim ](bg:#88C0D0 fg:#090c0c)\
[](bg:#4C566A fg:#88C0D0)\
$directory\
[](fg:#4C566A bg:#434C5E)\
$git_branch\
$git_status\
[](fg:#434C5E bg:#3B4252)\
$nodejs\
$rust\
$golang\
$php\
[ ](fg:#3B4252)\
\n$character"""

[directory]
style = "bg:#4C566A"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#434C5E"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#434C5E"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#434C5E"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#434C5E"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#434C5E"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#434C5E"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#434C5E"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#434C5E"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#434C5E"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#434C5E"
format = '[[ $symbol ($version) ](fg:#4C566A bg:#3B4252)]($style)'

[nim]
symbol = " "
style = "bg:#434C5E"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#434C5E"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ $time ]($style)'
